export default {
      COLLECTION_FETCHING_START: 'COLLECTION_FETCHING_START',
      COLLECTION_FETCHING_SUCCESS: 'COLLECTION_FETCHING_SUCCESS',
      COLLECTION_FETCHING_FAIL: 'COLLECTION_FETCHING_FAIL'
}